---
title: "assignment_5"
author: "Alia Ajina and Sophia Leiker"
date: "3/8/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(testthat)
library(purrr)
library(devtools)
```

```{r }
# Creating our initial lake level dataset
initial_level <- c(100000,120000,140000,160000)

# Creating our random sample of daily precipitation inputs
nsample = 4
precip_data = rnorm(mean = 10, sd = 2, n=nsample)
precip_results = data.frame(precip_data=precip_data)

# Combining into 1 dataframe
possible_lake <- data.frame(initial_level, precip_results)

#checking the outputs
head(possible_lake)
```

```{r, by hand checking that our function works}
source(here("R", "lake_equation.R"))

# Checking that our function works

lake_vol(100,10)
```

```{r}
outflow = c(10,10,10,10)
evap = c(1,1,1,1)

lake_1 = pmap(list(outflow, evap), lake_vol, initial_level = possible_lake$initial_level, precip_data = possible_lake$precip_data)

lake_2 = pmap(list(outflow, evap), lake_vol, initial_level = possible_lake$initial_level, precip_data = possible_lake$precip_data)

lake1_data = as.data.frame(lake_1)

```

Trying something new here
```{r}
# Creating our initial lake level dataset
initial_level <- c(100000,120000,140000,160000)

# Creating our random sample of daily precipitation inputs
nsample = 4
precip_data = rnorm(mean = 10, sd = 2, n=nsample)
precip_results = data.frame(precip_data=precip_data)

#creating inflow and outflow 
outflow = c(10,10,10,10)
evap = c(1,1,1,1)



# Combining into 1 dataframe
possible_lake2 <- data.frame(initial_level, outflow, evap)

#checking the outputs
head(possible_lake2)


lake_2 = pmap(list(initial_level = initial_level, outflow = outflow, evap = evap), lake_vol, precip_data = precip_data)

print(lake_2)

lake2_data = as.data.frame(lake_2, col.names = possible_lake2$initial_level)
print(lake2_data)
```


```{r}
# how do we run each car for all speeds, we use a for loop to cycle through, we need to create a data frame to store results - as above, one column for each car and one row for each speed

powerall3 = as.data.frame(matrix(nrow=length(precip_data), ncol=nrow(possible_lake2)))
# because we don't initialize it - values are NA
#head(powerall3)

# how many cars area there
#nrow(possible_cars)

# for loops use an index - in this case "i" but you could use anything - it repeats
# anything between the {} for each values of i between 1 and nrow(possible_car) (which is 3 in our case)

# index in to a matrix (like powerall3) is by row and column powerall3[2,5] is 2nd row and 5th column
for (i in 1:nrow(possible_lake2)) {
  powerall3[,i] = lake_vol(initial_level=possible_lake2$initial_level[i], outflow = possible_lake2$outflow[i],evap = possible_lake2$evap[i], precip_data = precip_data)
}

# now it looks like above
#head(powerall3)
# we can add column names
colnames(powerall3)=possible_lake2$initial_level

# plotting is the same as above

# for plotting sometimes its useful to turn columns in to rows
powerallr3 = powerall3 %>% pivot_longer(cols=everything(), names_to="initial_level", values_to="lake_vol")
head(powerallr3)

```

